### PR TITLE
refactor: replace window.ipfs with ipfs-provider

### LINKED ISSUE #3: Use ipfs-http-client or archive this repo
Since there is no `window.ipfs` anymore, we either need to refactor this demo to use [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client) or archive it and move to [ipfs-inactive/](https://github.com/ipfs-inactive/window.ipfs-fallback) org.

@hacdias will you have the bandwidth to do the refactor? If not, lmk, I'll do the archiving and moving.

### PR DESCRIPTION
**Pull request by hacdias**
Moves away from `window.ipfs` and uses `ipfs-provider` instead to try on default URL and on origin. Closes #3.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel basically finished I think. Is there any way to get the address IPFS Companion is connected to? That would be useful.

**Review by lidel — CHANGES_REQUESTED** [review]
No, there is no safe/future-proof way of exposing API via Companion atm.

LGTM, but can we remove `dist/` from repo and add it to `.gitignore`?

**Comment by hacdias** [comment]
Done @lidel. The CID should be pinning: https://twitter.com/hacdias/status/1403335052470231044

**Comment by lidel** [comment]
Thanks!

**Pull request merged**
